### ISSUE TITLE
how to run in other data?

### ISSUE THREAD

**Issue by johnbager** [zyang-ur/ReSC#1]
hello, i have a question about if i want to run in refcoco/refcocog to see the perferance in your paper,what setting i need to do?
just about the  "python train.py --data_root ./ln_data/ --dataset refcoco \
  --gpu gpu_id --resume saved_models/ReSC_base_refcoco.pth.tar"   is ok?

**Comment by zyang-ur** [comment]
Yes, that should work.

Please let me know if you met any problem :)

**Comment by johnbager** [comment]
yeah,I have found "refcoco" is wrong.  It's should be "  --dataset unc".

**Comment by johnbager** [comment]
so, I think if refcoco+ should be "unc+"?

**Comment by zyang-ur** [comment]
referit/flickr/unc/unc+/gref (https://github.com/zyang-ur/ReSC/blob/e4022f87bfd11200b67c4509bb9746640834ceae/train.py#L61)

Sorry for missed that :)

**Comment by johnbager** [comment]
yeah,thanks.    could you remember how long time do you use to run in  refcoco?
