### ISSUE TITLE
How to generate the index files like referit_train.pth in data.tar?

### ISSUE THREAD

**Issue by laoyandujiang** [zyang-ur/ReSC#2]
Hi,
Thank you for the great work! 
When I run the training process for referit dataset, I notice the indexs of training data are loaded from referit_train.pth which is extracted from data.tar you provided. We will obtained a list for every mask after loading referit_train.pth. The length of this list is 5, and my question is for the meaning of the fifth item in the list. For example, the fifth item is a list [('r1', ['bag']), ('r2', ['black']), ('r3', ['none']), ('r4', ['right']), ('r5', ['none']), ('r6', ['none']), ('r7', ['none']), ('r8', ['none'])] when the query is 'right black bag'. I cannot understand how to generate a list like it. Would you please explain its generating process? Thanks a lot!

**Comment by zyang-ur** [comment]
Hi, thank you for the question :)
I assume the question is how to get the parsed query like "[('r1', ['bag']), ('r2', ['black']), ('r3', ['none']), ('r4', ['right']), ('r5', ['none']), ('r6', ['none']), ('r7', ['none']), ('r8', ['none'])]."

We obtain these parsed results based on Licheng's parser in this repo: https://github.com/lichengunc/refer-parser2. They provide both the parsed results and the parser in case that you wish to try it on other datasets.

**Comment by laoyandujiang** [comment]
Thanks a lot for your detailed explanation. I observe that this parsed query has no contribution to the training (if my understanding is correct). I wonder if the parsed query could be directly ignored in the code of ReSC, supposing one wants to train the model with customized datasets.

**Comment by zyang-ur** [comment]
Yes, you can safely ignore these parsed queries. I use them for results analyses only.

**Comment by laoyandujiang** [comment]
Get it. Your explanation help me a lot. Thank you very much.
