### ISSUE TITLE
mistake in train.py for anchor settings

### ISSUE THREAD

**Issue by nku-shengzheliu** [zyang-ur/ReSC#5]
Hi zhengyuan!
At line 107 of the `train.py file`, it should be **'referit'** and not **'refeit'**.
I found this problem when loading the `ReSC_base_referit.tar` model file you provided to run on the test set.
The test set performance was 35% when I used anchor set:
```
if args.dataset=='refeit':
        anchors = '30,36,  78,46,  48,86,  149,79,  82,148,  331,93,  156,207,  381,163,  329,285'
```
and reached the performance reported in the paper when I used anchor set:
```
else:
        anchors = '10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326'
```

**Comment by zyang-ur** [comment]
Hi @nku-shengzheliu,

Thank you so much for catching this!

I'll remove the referit-specific anchor, and add a comment to point to this issue for reference.

Thank you :)
