### ISSUE TITLE
About data  preparation

### ISSUE THREAD

**Issue by yuanze-lin** [zyang-ur/ReSC#6]
I cannot download split files, the link is "https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2". Can you share this file in TransVG repo ? Thanks a lot !

**Comment by zyang-ur** [comment]
Hi @yzleroy ,

I'm not sure if I have the proper copyright to share the data publicly. Feel free to send me an email and we could discuss how to help you get the data. Thank you.

**Comment by CoCNetHub** [comment]
Have you solved it? I have the same problem

**Comment by akira-l** [comment]
The same problem. How to download the dataset?

**Comment by zyang-ur** [comment]
Feel free to send me an email and we could discuss how to help you get the data. Thank you.
